eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5

#mq配置
spring:
    rabbitmq:
        host: 192.168.63.10
        port: 5672
        virtual-host: /hd
        username: admin
        password: 123456
    cloud:
        bus:
            enabled: true
            trace:
                enabled: true
#运行状态监控
management:
    endpoints:
        web:
            exposure:
                include: bus-refresh
